//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LAVAudio.rc
//
#define IDD_PROPPAGE_AUDIO_SETTINGS     9
#define IDD_PROPPAGE_AUDIO_MIXING       10
#define IDD_PROPPAGE_FORMATS            11
#define IDD_PROPPAGE_STATUS             12
#define IDS_SETTINGS                    101
#define IDS_STATUS                      102
#define IDS_FORMATS                     103
#define IDI_ICON1                       104
#define IDS_MIXER                       105
#define IDC_INPUT_STATUS                1013
#define IDC_OUTPUT_STATUS               1026
#define IDC_DRC                         1034
#define IDC_DRC_LEVEL                   1035
#define IDC_DRC_BOX                     1036
#define IDC_DRC_LEVEL_TEXT              1037
#define IDC_LBL_DRC_LEVEL               1038
#define IDC_VOLUME                      1039
#define IDC_VOLUME1                     1040
#define IDC_VOLUME2                     1041
#define IDC_VOLUME3                     1042
#define IDC_VOLUME4                     1043
#define IDC_VOLUME5                     1044
#define IDC_VOLUME6                     1045
#define IDC_VOLUME7                     1046
#define IDC_VOLUME8                     1047
#define IDC_VOLUME1_DESC                1048
#define IDC_VOLUME2_DESC                1049
#define IDC_VOLUME3_DESC                1050
#define IDC_VOLUME4_DESC                1051
#define IDC_VOLUME5_DESC                1052
#define IDC_VOLUME6_DESC                1053
#define IDC_VOLUME7_DESC                1054
#define IDC_VOLUME8_DESC                1055
#define IDC_CODECS                      1056
#define IDC_CODECS_NONE                 1059
#define IDC_LAVAUDIO_FOOTER             1060
#define IDC_BITSTREAMING                1061
#define IDC_BS_AC3                      1062
#define IDC_BS_EAC3                     1063
#define IDC_BS_TRUEHD                   1064
#define IDC_BS_DTS                      1065
#define IDC_BS_DTSHD                    1066
#define IDC_BS_FORMATS                  1067
#define IDC_BS_DTSHD_FRAMING            1068
#define IDC_BS_OPTIONS                  1069
#define IDC_OPTIONS                     1070
#define IDC_AUTO_AVSYNC                 1071
#define IDC_LBL_INPUT_CODEC             1072
#define IDC_LBL_INPUT_CHANNEL           1073
#define IDC_LBL_INPUT_SAMPLERATE        1074
#define IDC_LBL_INPUT_FORMAT            1075
#define IDC_INPUT_SAMPLERATE            1076
#define IDC_INPUT_CODEC                 1077
#define IDC_INPUT_CHANNEL               1078
#define IDC_INPUT_FORMAT                1079
#define IDC_LBL_OUTPUT_CODEC            1080
#define IDC_LBL_OUTPUT_CHANNEL          1081
#define IDC_LBL_OUTPUT_SAMPLERATE       1082
#define IDC_LBL_OUTPUT_FORMAT           1083
#define IDC_OUTPUT_SAMPLERATE           1084
#define IDC_OUTPUT_CODEC                1085
#define IDC_OUTPUT_CHANNEL              1086
#define IDC_OUTPUT_FORMAT               1087
#define IDC_STANDARD_CH_LAYOUT          1088
#define IDC_EXPAND_MONO                 1089
#define IDC_EXPAND61                    1090
#define IDC_OUTPUT_FORMATS              1091
#define IDC_LBL_OUTPUTFORMATS           1092
#define IDC_OUT_S16                     1093
#define IDC_OUT_S24                     1094
#define IDC_OUT_S32                     1095
#define IDC_OUT_FP32                    1096
#define IDC_OUT_U8                      1097
#define IDC_LBL_OUTNOTE                 1098
#define IDC_GROUP_DELAY                 1099
#define IDC_DELAY_ENABLED               1100
#define IDC_DELAY                       1101
#define IDC_DELAYSPIN                   1102
#define IDC_LBL_FORMATS                 1103
#define IDC_MIXING                      1104
#define IDC_MIXER                       1105
#define IDC_DOWNMIX                     1106
#define IDC_OUTPUT_SPEAKERS             1108
#define IDC_UNTOUCHED_STEREO            1109
#define IDC_MIX_SETTINGS                1110
#define IDC_LBL_OUTPUT_SPEAKERS         1111
#define IDC_LBL_MIXING                  1112
#define IDC_NORMALIZE_MATRIX            1113
#define IDC_CLIP_PROTECTION             1114
#define IDC_MIXING_MODE                 1115
#define IDC_MIXMODE_NORMAL              1116
#define IDC_MIXMODE_DOLBY               1117
#define IDC_MIXMODE_DPL2                1118
#define IDC_MIX_LEVEL_CENTER            1121
#define IDC_MIX_LEVEL_SURROUND          1122
#define IDC_MIX_LEVEL_LFE               1123
#define IDC_LBL_CENTER_LEVEL            1124
#define IDC_LBL_SURROUND_LEVEL          1125
#define IDC_LBL_LFE_LEVEL               1126
#define IDC_MIX_LEVEL_CENTER_TEXT       1127
#define IDC_MIX_LEVEL_SURROUND_TEXT     1128
#define IDC_MIX_LEVEL_LFE_TEXT          1129
#define IDC_LBL_MIXING_LEVEL            1130
#define IDC_TRAYICON                    1131
#define IDC_OUT_S16_DITHER              1132
#define IDC_OUTPUT51_LEGACY             1133
#define IDC_BS_FALLBACK                 1135

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1134
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
